Repository yuhuinc/yuhui, pull requests merged in 2020-04, with the labels that each got.

#13 Styling changes for input file
  package.json
  src/Input/InputFile.tsx
  stories/components/Input/InputFile.stories.tsx
Labels: bug

#14 Add tests
  .github/workflows/test.yml
  babel.config.js
  jest.config.js
  package.json
  src/Button/Button.test.tsx
  src/Button/__snapshots__/Button.test.tsx.snap
  src/testUtils.tsx
  yarn.lock
Labels: chore

#15 Create centred dialog component
  README.md
  package.json
  src/Dialog/DialogCentreScreen.tsx
  src/index.ts
  stories/components/Dialog/Dialog.md
  stories/components/Dialog/DialogCentreScreen.stories.tsx
  stories/components/Dialog/DialogFullScreen.stories.tsx
Labels: enhancement

#16 Pass rest of props to centred dialog
  src/Dialog/DialogCentreScreen.tsx
Labels: chore

#17 Confirmation dialog recipe
  package.json
  src/Content/Content.tsx
  src/Dialog/DialogCentreScreen.tsx
  stories/components/Dialog/Dialog.md
  stories/components/Dialog/DialogCentreScreen.stories.tsx
  stories/recipes/ConfirmationDialog.stories.tsx
Labels: enhancement
