Repository yuhuinc/yuhui, pull requests merged in 2020-03, with the labels that each got.

#7 NumberInput component
  src/Input/NumberInput.tsx
  src/index.ts
  src/shared/constants.ts
  stories/components/NumberInput/NumberInput.md
  stories/components/NumberInput/NumberInput.stories.tsx
Labels: enhancement

#6 7014 - file collection component using dropzone
  globals.d.ts
  package.json
  src/FileCollection/FileCollection.tsx
  src/FileCollection/file-drop.png
  src/InputCollection/InputCollection.tsx
  src/index.ts
  src/shared/constants.ts
  stories/components/FileCollection/FileCollection.md
  stories/components/FileCollection/FileCollection.stories.tsx
  stories/components/InputCollection/InputCollection.stories.tsx
  yarn.lock
Labels: enhancement

#8 change some file names for better unity and make adjustments accordingly
  package.json
  src/Button/ButtonPrimary.tsx
  src/Input/InputCollection.tsx
  src/Input/InputFile.tsx
  src/Input/InputNumber.tsx
  src/Input/file-drop.png
  src/index.ts
  stories/components/Input/Dialog.stories.tsx
  stories/components/Input/Input.stories.tsx
  stories/components/Input/InputCollection.md
  stories/components/Input/InputCollection.stories.tsx
  stories/components/Input/InputFile.md
  stories/components/Input/InputFile.stories.tsx
  stories/components/Input/InputNumber.md
  stories/components/Input/InputNumber.stories.tsx
  stories/components/Input/RadioCards.stories.tsx
Labels: chore

#9 fix color chaining to work with default colors
  src/Input/InputFile.tsx
  stories/components/Input/InputFile.stories.tsx
Labels: bug

#11 Fix undefined color file input
  package.json
  src/Input/InputFile.tsx
Labels: bug
